<?php
/**
 * @file
 * Provide a marquee element.
 */

/**
 * Implements hook_menu().
 */
function marquee_menu() {
  $items = array();
  $items['admin/config/system/marquee'] = array(
    'title' => 'Marqee',
    'description' => 'Configurate the marquee settings for your site.',
    'route_name' => 'marquee.settings',
    'weight' => 20,
  );
  return $items;
}

/**
 * Implements hook_page_alter().
 */
function marquee_page_alter(&$page) {
  $enabled = \Drupal::config('marquee.settings')
    ->get('enabled');

  $path = \Drupal::request()->getPathInfo();

  if ($enabled && $path != '/admin/config/system/marquee') {
    $page = _marquee_page_alter($page);
  }
}


/**
 * Implements hook_element_info().
 */
function marquee_element_info() {
  $types = array();
  // The key of the array will become the element #type. For example,
  // #type => 'marquee'.
  $types['marquee'] = array(
    '#theme' => 'marquee_marquee',
  );
  return $types;
}

/**
 * Implements hook_theme().
 */
function marquee_theme() {
  return array(
    'marquee_wrapper' => array(
      'template' => 'marquee-wrapper',
      'render element' => 'element',
    ),
  );
}

/**
 * Preprocess function for marquee-wrapper.html.twig.
 */
function template_preprocess_marquee_wrapper(&$variables) {
  $variables['amount'] = abs(rand(1, 50));
  $variables['direction'] = (abs(rand(0, 1)) == 1) ? 'left' : 'right';
  $variables['content'] = $variables['element']['#children'];
}

/**
 * Helper function to recursively apply a #theme_wrapper to nested elements.
 */
function _marquee_page_alter($element) {
  $element['#theme_wrappers'][] = 'marquee_wrapper';
  foreach (element_children($element) as $key) {
    $element[$key] = _marquee_page_alter($element[$key]);
  }
  return $element;
}
